Improved error handling

diff --git a/sync b/sync
--- a/sync
+++ b/sync
@@ -1,6 +1,7 @@
 # mxfng.sync | Run to sync dotfiles to $HOME and brew bundle.
 
 BASEDIR="$(dirname "$(realpath -s "$0")")"
+ERROUT=false; ERRC=0
 
 brewsync()  # Installs dependencies Homebrew and Git
 {
@@ -21,14 +22,11 @@ gitsync()   # Remote pull or remote clone
 
     if [ -d .git ]; then
         echo Pulling remote
-        git pull || exit 1  # Update Repository
+        git pull
     else
         echo Cloning remote
         mkdir -p $LOCAL_REPO
-        git clone https://github.com/mxfng/dotfiles $LOCAL_REPO ||\
-        echo "There were 1 or more errors during sync."\
-        echo "Please reference the output above for more information on the error(s)."\
-        echo Syncing mxfng.dotfiles failed
+        git clone https://github.com/mxfng/dotfiles $LOCAL_REPO
         cd $LOCAL_REPO
     fi
 }
@@ -57,10 +55,8 @@ arm64cleanup()  # Addresses any M1-specific issues
 }
 
 # Simple error handling
-set -e
-trap "echo -e '\e[1;31mThere were 1 or more errors during sync.\e[0m';
-echo -e '\e[1;31mPlease reference the output above for more information on the error(s).\e[0m'
-echo 'Syncing mxfng.dotfiles failed'" EXIT
+#set -e
+trap "ERROUT=true; ERRC=$((ERRC+1))" ERR
 
 # ----------------------------------------------------------------
 
@@ -97,6 +93,12 @@ ln -s $PWD/.config/git/.gitconfig ~/.gitconfig
 # ~/ Setup
 mkdir -p ~/.cache/zsh ~/.nvm ~/Developer  ~/.local/bin/$USER
 
-echo -e "User-defined shell config files go in \`~/.local/bin/${USER}\`m"
-echo -e 'Restart your shell to reflect sync or run `source ~/.zprofile ~/.zshrc`'
-echo -e '\e[1;32mSynced mxfng.dotfiles\e[0m'
+if $ERROUT; then
+    echo -e "\e[1;31mThere were $ERRC or more errors during sync.\e[0m"
+    echo -e '\e[1;31mPlease reference the output above for more information on the error(s).\e[0m'
+    echo -e '\e[1;31mSyncing mxfng.dotfiles failed\e[0m'
+else
+    echo "User-defined shell config files go in \`~/.local/bin/${USER}\`m"
+    echo 'Restart your shell to reflect sync or run `source ~/.zprofile ~/.zshrc`'
+    echo -e '\e[1;32mSynced mxfng.dotfiles\e[0m'
+fi
