update sync

diff --git a/sync b/sync
--- a/sync
+++ b/sync
@@ -15,38 +15,38 @@ command_exists() {
 
 # Download iTerm2 Shell Integration for Zsh
 sync_iterm2() {
-    if curl -L https://iterm2.com/shell_integration/zsh -o $ITERM2_ZSH_PATH; then
-        touch ~/.hushlogin          # Silence prompt at login
-    else
-        echo "Failed to download iTerm2 Shell Integration for Zsh"
-        exit 1
+    if [[ "$OSTYPE" == "darwin"* ]]; then
+        if curl -L https://iterm2.com/shell_integration/zsh -o $ITERM2_ZSH_PATH; then
+            touch ~/.hushlogin          # Silence prompt at login
+        else
+            echo "Failed to download iTerm2 Shell Integration for Zsh"
+            exit 1
+        fi
     fi
 }
 
-sync_brew()  # Installs dependencies Homebrew and Git
-{
-    which -s brew
-    if [[ $? != 0 ]] ; then
-        echo Installing Homebrew
+# Ensures brew is installed and installs git
+ensure_brew_and_git() {
+    if ! command_exists brew; then
+        echo "Installing Homebrew"
         /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-        eval "$(/opt/homebrew/bin/brew shellenv)"
-        brew install wget
         brew doctor
         brew install git
     fi
 }
 
-sync_git()   # Remote pull or remote clone
-{
+# Checks if a directory exists and if it contains a .git directory
+# If it does, it pulls the latest changes, otherwise it clones the repository
+sync_git() {
     if [ -d $LOCAL_REPO ] && [ ! -d .git ]; then
         cd $LOCAL_REPO
     fi
 
     if [ -d .git ]; then
-        echo Pulling remote
+        echo "Pulling remote"
         git pull
     else
-        echo Cloning remote
+        echo "Cloning remote"
         mkdir -p $LOCAL_REPO
         git clone https://github.com/mxfng/dotfiles $LOCAL_REPO
         cd $LOCAL_REPO
@@ -57,52 +57,61 @@ sync_git()   # Remote pull or remote clone
     fi
 }
 
-sync_zsh()   # Swaps to brew zsh and adds iTerm2 Shell Integration
-{
+sync_brew() {
+    if command_exists brew; then
+        echo Running Brewfile
+        brew update; brew upgrade
+
+        brew bundle --force cleanup
+
+        # Wipe Brewfile debugging output
+        rm -f $PWD/Brewfile.lock.json
+    else
+        echo "brew command not found"
+        exit 1
+    fi
+}
+
+# Swaps to brew zsh and adds iTerm2 Shell Integration
+sync_zsh() {
     if [[ $(which zsh) != "$(brew --prefix)/bin/zsh" ]]; then
         echo Current active Zsh will swap to $(which zsh)
         chsh -s $(which zsh)    # Set Default Shell to Homebrew Zsh
     fi
+}
 
-    if [[ "$OSTYPE" == "darwin"* ]]; then
-        # iTerm2 Shell Integration for Zsh
-        curl -L https://iterm2.com/shell_integration/zsh \
-        -o $PWD/.config/iTerm2/.iterm2_shell_integration.zsh
-        touch ~/.hushlogin          # Silence prompt at login
+sync_asdf() {
+    if command_exists asdf; then
+        echo "Ensuring ASDF is synchronized with Ruby, NodeJS, and Yarn"
+
+        # Add plugins if they don't exist
+        asdf plugin list | grep -q ruby || asdf plugin add ruby
+        asdf plugin list | grep -q nodejs || asdf plugin add nodejs
+
+        # Install ruby version if it's not already installed
+        asdf list ruby | grep -q 3.3.0 || asdf install ruby 3.3.0
+        asdf global ruby 3.3.0
+
+        gem update --system
+        echo "Warning: gem update --system may require sudo access"
+
+        # Install nodejs version if it's not already installed
+        asdf list nodejs | grep -q 20.11.0 || asdf install nodejs 20.11.0
+        asdf global nodejs 20.11.0
+
+        # Check if yarn is installed, if not install it
+        npm list -g --depth=0 | grep -q yarn || npm install -g yarn
+
+        # Check if Rails is installed, if not install it
+        if ! command_exists rails; then
+            sudo asdf exec gem install rails -v 7.1.3
+        fi
+        
     fi
 }
 
-# Sync dotfiles
-sync_dotfiles() {
-    echo Syncing mxfng.dotfiles.$OSTYPE
-
-    cd $BASEDIR; LOCAL_REPO=~/Developer/dotfiles
-
-    if [[ "$OSTYPE" == "darwin"* ]]; then
-        if command_exists brew; then
-            sync_brew
-        else
-            echo "brew command not found"
-            exit 1
-        fi
-    fi
-
-    sync_git
-
-    if [[ "$OSTYPE" == "darwin"* ]]; then
-        if command_exists brew; then
-            echo Running Brewfile
-            brew update; brew upgrade; brew bundle
-        else
-            echo "brew command not found"
-            exit 1
-        fi
-    fi
-
-    sync_zsh
-
-    # Wipe Brewfile debugging output
-    rm -f $PWD/Brewfile.lock.json
+sync_directories() {
+    echo "Syncing .config files to $HOME"
 
     # Rm .config files to swap in $HOME
     for DOTFILE in "${DOTFILES[@]}"; do
@@ -120,6 +129,20 @@ sync_dotfiles() {
     mkdir -p ~/.cache/zsh ~/.cache/node ~/.nvm ~/Developer  ~/.local/bin/$USER
 }
 
+# Sync dotfiles
+main() {
+    echo Syncing mxfng.dotfiles.$OSTYPE
+
+    cd $BASEDIR; LOCAL_REPO=~/Developer/dotfiles
+
+    ensure_brew_and_git
+    sync_git
+    sync_brew
+    sync_zsh
+    sync_asdf
+    sync_directories  
+}
+
 # Main
 case "$1" in
 -h|--help)
@@ -131,7 +154,7 @@ case "$1" in
     exit 0
     ;;
 *)
-    sync_dotfiles
+    main
     ;;
 esac
 
