update sync

diff --git a/sync b/sync
--- a/sync
+++ b/sync
@@ -3,10 +3,27 @@
 # mxfng.sync | Run to sync dotfiles to $HOME and brew bundle.
 
 BASEDIR="$(dirname "$(readlink -f "$0")")"
+ITERM2_ZSH_PATH="$PWD/.config/iTerm2/.iterm2_shell_integration.zsh"
+DOTFILES=(~/.zprofile ~/.zshrc ~/.gitconfig)
 ERROUT=false; ERRC=0    # ERROR flag and counter
 trap "ERROUT=true; ERRC=$((ERRC+1))" ERR
 
-brewsync()  # Installs dependencies Homebrew and Git
+# Check if a command exists
+command_exists() {
+    command -v "$1" >/dev/null 2>&1
+}
+
+# Download iTerm2 Shell Integration for Zsh
+sync_iterm2() {
+    if curl -L https://iterm2.com/shell_integration/zsh -o $ITERM2_ZSH_PATH; then
+        touch ~/.hushlogin          # Silence prompt at login
+    else
+        echo "Failed to download iTerm2 Shell Integration for Zsh"
+        exit 1
+    fi
+}
+
+sync_brew()  # Installs dependencies Homebrew and Git
 {
     which -s brew
     if [[ $? != 0 ]] ; then
@@ -40,7 +57,7 @@ gitsync()   # Remote pull or remote clone
     fi
 }
 
-zshsync()   # Swaps to brew zsh and adds iTerm2 Shell Integration
+sync_zsh()   # Swaps to brew zsh and adds iTerm2 Shell Integration
 {
     if [[ $(which zsh) != "$(brew --prefix)/bin/zsh" ]]; then
         echo Current active Zsh will swap to $(which zsh)
@@ -55,42 +72,58 @@ zshsync()   # Swaps to brew zsh and adds iTerm2 Shell Integration
     fi
 }
 
-# ----------------------------------------------------------------
+# Sync dotfiles
+sync_dotfiles() {
+    echo Syncing mxfng.dotfiles.$OSTYPE
 
-echo Syncing mxfng.dotfiles.$OSTYPE
+    cd $BASEDIR; LOCAL_REPO=~/Developer/dotfiles
 
-cd $BASEDIR; LOCAL_REPO=~/Developer/dotfiles
+    if [[ "$OSTYPE" == "darwin"* ]]; then
+        if command_exists brew; then
+            sync_brew
+        else
+            echo "brew command not found"
+            exit 1
+        fi
+    fi
 
-if [[ "$OSTYPE" == "darwin"* ]]; then brewsync; fi
+    sync_git
 
-gitsync         # Git remote pull or clone
+    if [[ "$OSTYPE" == "darwin"* ]]; then
+        if command_exists brew; then
+            echo Running Brewfile
+            brew update; brew upgrade; brew bundle
+        else
+            echo "brew command not found"
+            exit 1
+        fi
+    fi
 
-if [[ "$OSTYPE" == "darwin"* ]]; then
-    echo Running Brewfile
-    brew update; brew upgrade; brew bundle    # Run Brewfile
-fi
+    sync_zsh
 
-zshsync         # Swap to Homebrew zsh; add iTerm 2
+    # Wipe Brewfile debugging output
+    rm -f $PWD/Brewfile.lock.json
 
-rm -f $PWD/Brewfile.lock.json   # Wipe Brewfile debugging output
+    # Rm .config files to swap in $HOME
+    for DOTFILE in "${DOTFILES[@]}"; do
+        rm -f $DOTFILE
+    done
 
-# Rm .config files to swap in $HOME
-for DOTFILE in ~/.zprofile ~/.zshrc ~/.gitconfig; do
-    rm -f $DOTFILE
-done
+    # Source .config files in $HOME
+    echo "source ${PWD}/.config/shell/profile" >> ~/.zprofile
+    echo "source ${PWD}/.config/zsh/.zshrc" >> ~/.zshrc
 
-# Source .config files in $HOME
-echo "source ${PWD}/.config/shell/profile" >> ~/.zprofile
-echo "source ${PWD}/.config/zsh/.zshrc" >> ~/.zshrc
+    # Symlink .config files in $HOME
+    ln -s $PWD/.config/git/.gitconfig ~/.gitconfig
 
-# Symlink .config files in $HOME
-ln -s $PWD/.config/git/.gitconfig ~/.gitconfig
+    # ~/ Setup
+    mkdir -p ~/.cache/zsh ~/.cache/node ~/.nvm ~/Developer  ~/.local/bin/$USER
+}
 
-# ~/ Setup
-mkdir -p ~/.cache/zsh ~/.cache/node ~/.nvm ~/Developer  ~/.local/bin/$USER
+sync_dotfiles
 
 if $ERROUT; then
-    echo -e "\e[1;31mThere were $ERRC or more errors during sync.\e[0m"
+    echo -e "\e[1;31mThere were $ERRC error(s) during sync.\e[0m"
     echo -e '\e[1;31mPlease reference the output above for more information on the error(s).\e[0m'
     echo -e '\e[1;31mSyncing mxfng.dotfiles failed\e[0m'
 else
